import './globals.css';
import React, { ReactNode } from 'react';
import type { Metadata } from 'next';
import Providers from './Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col bg-gray-200 p-4">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
